FROM node:12.5.0-alpine

ARG WORKDIR
ARG CONTAINER_PORT
ARG API_URL

ENV HOME=/${WORKDIR} \
    LANG=C.UTF-8 \
    TZ=Asia/Tokyo \
    HOST=0.0.0.0 \
    API_URL=${API_URL}
# ENV PATH ${HOME}/node_modules/.bin:$PATH

WORKDIR ${HOME}

COPY package.json .
COPY . .

RUN apk update && \
    apk upgrade && \
    npm install -g n && \
    rm -rf /var/cache/apk/*

RUN yarn install

RUN yarn run build

EXPOSE ${CONTAINER_PORT}

CMD ["yarn", "start"]